# Generated by Django 5.2.11 on 2026-02-11 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('degree_level', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTERS', 'Masters'), ('PHD', 'PhD'), ('NO_DEGREE', 'No Degree')], max_length=20)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('application_link', models.URLField()),
                ('deadline', models.DateField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('UPCOMING', 'Upcoming'), ('ENDED', 'Ended'), ('EXTENDED', 'Extended')], default='OPEN', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
