# Generated by Django 5.2.3 on 2026-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='degree_level',
            field=models.CharField(choices=[('ORGANIZATION CERTIFICATE ', ' Organization Certificate(OGC)'), (' ADVANCED DIPLOMA', 'Advanced Diploma(A2)'), ('BACHELOR of degree', 'Bachelor of degree(BSc)'), ('MASTERS DEGREE', 'Masters Degree(MSc)'), ('PHD DEGREE', 'PhD Degree(PHD)'), ('NO_DEGREE', 'No Degree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scholarship_images/'),
        ),
    ]
