# Generated by Django 5.2.3 on 2026-02-11 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarship_degree_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='degree_level',
            field=models.CharField(choices=[('ORGANIZATION_CERTIFICATE', 'Organization Certificate (OGC)'), ('ADVANCED_DIPLOMA', 'Advanced Diploma (A2)'), ('BACHELOR_DEGREE', 'Bachelor of Degree (BSc)'), ('MASTERS_DEGREE', 'Masters Degree (MSc)'), ('PHD_DEGREE', 'PhD Degree (PhD)'), ('NO_DEGREE', 'No Degree')], max_length=50),
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('cell', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], max_length=10)),
                ('highest_qualification', models.TextField(blank=True, max_length=200)),
                ('education_background', models.TextField(help_text='Describe your education background from top to higher level')),
                ('CV_file_upload', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('application_Lettle', models.FileField(blank=True, null=True, upload_to='application_lettle/')),
                ('photo', models.ImageField(upload_to='application/photo')),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_address', models.CharField(max_length=900)),
                ('guardian_location', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254, unique=True)),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('visa', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
