# Generated by Django 5.2.3 on 2026-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_alter_scholarship_degree_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
