# Generated by Django 5.2.3 on 2026-02-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_scholarship_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
