# Generated by Django 5.2.3 on 2026-02-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FursaLink_ChatBox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samhubchat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FursaLink_ChatBox.samhubchat'),
        ),
    ]
