# Generated by Django 5.2.3 on 2026-02-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FursaLink_ChatBox', '0003_message_comment_delete_samhubchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
