# Generated by Django 5.2.3 on 2026-02-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FursaLink_ChatBox', '0004_comment_deleted_by_admin_message_deleted_by_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
