# Generated by Django 5.2.3 on 2026-02-12 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('YES', 'Experience Required'), ('NO', 'No Experience Required')], default='NO', max_length=3),
        ),
        migrations.CreateModel(
            name='JobDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_docs/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Job_Opportunity.job')),
            ],
        ),
    ]
