# Generated by Django 5.2.3 on 2026-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Opportunity', '0003_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='require_cover_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='require_resume',
            field=models.BooleanField(default=True),
        ),
    ]
