# Generated by Django 5.2.3 on 2026-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Opportunity', '0004_job_require_cover_letter_job_require_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-site'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='required_documents_list',
            field=models.TextField(blank=True, help_text='List documents separated by commas'),
        ),
    ]
