# Generated by Django 5.2.3 on 2026-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Opportunity', '0005_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, help_text='Direct URL where applicants can apply themselves (e.g. company website)', null=True),
        ),
    ]
